//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduMSDemo.Resources.Views.Manage.Studies.SubjectClass.SubjectClassView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduMSDemo.Resources.Views.Manage.Studies.SubjectClass.SubjectClassView.Titles", typeof(Titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectClass.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Room.
        /// </summary>
        public static string RoomOfClassName {
            get {
                return ResourceManager.GetString("RoomOfClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midterm Exam Room.
        /// </summary>
        public static string RoomOfMidtermExamName {
            get {
                return ResourceManager.GetString("RoomOfMidtermExamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Exam Room.
        /// </summary>
        public static string RoomOfTermExamName {
            get {
                return ResourceManager.GetString("RoomOfTermExamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester.
        /// </summary>
        public static string SemesterName {
            get {
                return ResourceManager.GetString("SemesterName", resourceCulture);
            }
        }
    }
}
