//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduMSDemo.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentTitles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentTitles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduMSDemo.Resources.Shared.ContentTitles", typeof(ContentTitles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation.
        /// </summary>
        public static string AdministrationAccountsCreate {
            get {
                return ResourceManager.GetString("AdministrationAccountsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account delete.
        /// </summary>
        public static string AdministrationAccountsDelete {
            get {
                return ResourceManager.GetString("AdministrationAccountsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account details.
        /// </summary>
        public static string AdministrationAccountsDetails {
            get {
                return ResourceManager.GetString("AdministrationAccountsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account edit.
        /// </summary>
        public static string AdministrationAccountsEdit {
            get {
                return ResourceManager.GetString("AdministrationAccountsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AdministrationAccountsIndex {
            get {
                return ResourceManager.GetString("AdministrationAccountsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role creation.
        /// </summary>
        public static string AdministrationRolesCreate {
            get {
                return ResourceManager.GetString("AdministrationRolesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role deletion.
        /// </summary>
        public static string AdministrationRolesDelete {
            get {
                return ResourceManager.GetString("AdministrationRolesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role details.
        /// </summary>
        public static string AdministrationRolesDetails {
            get {
                return ResourceManager.GetString("AdministrationRolesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role edit.
        /// </summary>
        public static string AdministrationRolesEdit {
            get {
                return ResourceManager.GetString("AdministrationRolesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string AdministrationRolesIndex {
            get {
                return ResourceManager.GetString("AdministrationRolesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        public static string AdministrationSystemSettings {
            get {
                return ResourceManager.GetString("AdministrationSystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string AdministrationSystemSettingsCreate {
            get {
                return ResourceManager.GetString("AdministrationSystemSettingsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string AdministrationSystemSettingsDelete {
            get {
                return ResourceManager.GetString("AdministrationSystemSettingsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string AdministrationSystemSettingsDetails {
            get {
                return ResourceManager.GetString("AdministrationSystemSettingsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AdministrationSystemSettingsEdit {
            get {
                return ResourceManager.GetString("AdministrationSystemSettingsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        public static string AdministrationSystemSettingsIndex {
            get {
                return ResourceManager.GetString("AdministrationSystemSettingsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string AuthLogin {
            get {
                return ResourceManager.GetString("AuthLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string AuthRecover {
            get {
                return ResourceManager.GetString("AuthRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string AuthRegister {
            get {
                return ResourceManager.GetString("AuthRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string AuthReset {
            get {
                return ResourceManager.GetString("AuthReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string HomeError {
            get {
                return ResourceManager.GetString("HomeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeIndex {
            get {
                return ResourceManager.GetString("HomeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string HomeNotFound {
            get {
                return ResourceManager.GetString("HomeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string HomeUnauthorized {
            get {
                return ResourceManager.GetString("HomeUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ManagePartNoesDelete {
            get {
                return ResourceManager.GetString("ManagePartNoesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group.
        /// </summary>
        public static string ManageProductGroups {
            get {
                return ResourceManager.GetString("ManageProductGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ManageProductGroupsCreate {
            get {
                return ResourceManager.GetString("ManageProductGroupsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ManageProductGroupsDelete {
            get {
                return ResourceManager.GetString("ManageProductGroupsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ManageProductGroupsDetails {
            get {
                return ResourceManager.GetString("ManageProductGroupsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ManageProductGroupsEdit {
            get {
                return ResourceManager.GetString("ManageProductGroupsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group.
        /// </summary>
        public static string ManageProductGroupsIndex {
            get {
                return ResourceManager.GetString("ManageProductGroupsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string ManageProducts {
            get {
                return ResourceManager.GetString("ManageProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ManageProductsCreate {
            get {
                return ResourceManager.GetString("ManageProductsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ManageProductsDelete {
            get {
                return ResourceManager.GetString("ManageProductsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ManageProductsDetails {
            get {
                return ResourceManager.GetString("ManageProductsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ManageProductsEdit {
            get {
                return ResourceManager.GetString("ManageProductsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string ManageProductsIndex {
            get {
                return ResourceManager.GetString("ManageProductsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileDelete {
            get {
                return ResourceManager.GetString("ProfileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileEdit {
            get {
                return ResourceManager.GetString("ProfileEdit", resourceCulture);
            }
        }
    }
}
