//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduMSDemo.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Headers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Headers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduMSDemo.Resources.Shared.Headers", typeof(Headers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AdministrationAccounts {
            get {
                return ResourceManager.GetString("AdministrationAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AdministrationAccountsIndex {
            get {
                return ResourceManager.GetString("AdministrationAccountsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string AdministrationRoles {
            get {
                return ResourceManager.GetString("AdministrationRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string AdministrationRolesIndex {
            get {
                return ResourceManager.GetString("AdministrationRolesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AdministrationSystemSettings {
            get {
                return ResourceManager.GetString("AdministrationSystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AdministrationSystemSettingsIndex {
            get {
                return ResourceManager.GetString("AdministrationSystemSettingsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BonusScores.
        /// </summary>
        public static string ManageBonusScores {
            get {
                return ResourceManager.GetString("ManageBonusScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BonusScores.
        /// </summary>
        public static string ManageBonusScoresIndex {
            get {
                return ResourceManager.GetString("ManageBonusScoresIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildings.
        /// </summary>
        public static string ManageBuildings {
            get {
                return ResourceManager.GetString("ManageBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildings.
        /// </summary>
        public static string ManageBuildingsIndex {
            get {
                return ResourceManager.GetString("ManageBuildingsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassRooms.
        /// </summary>
        public static string ManageClassRooms {
            get {
                return ResourceManager.GetString("ManageClassRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassRooms.
        /// </summary>
        public static string ManageClassRoomsIndex {
            get {
                return ResourceManager.GetString("ManageClassRoomsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string ManageCourses {
            get {
                return ResourceManager.GetString("ManageCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string ManageCoursesIndex {
            get {
                return ResourceManager.GetString("ManageCoursesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurriculumDetails.
        /// </summary>
        public static string ManageCurriculumDetails {
            get {
                return ResourceManager.GetString("ManageCurriculumDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurriculumDetails.
        /// </summary>
        public static string ManageCurriculumDetailsIndex {
            get {
                return ResourceManager.GetString("ManageCurriculumDetailsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculums.
        /// </summary>
        public static string ManageCurriculums {
            get {
                return ResourceManager.GetString("ManageCurriculums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculums.
        /// </summary>
        public static string ManageCurriculumsIndex {
            get {
                return ResourceManager.GetString("ManageCurriculumsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurriculumTypes.
        /// </summary>
        public static string ManageCurriculumTypes {
            get {
                return ResourceManager.GetString("ManageCurriculumTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurriculumTypes.
        /// </summary>
        public static string ManageCurriculumTypesIndex {
            get {
                return ResourceManager.GetString("ManageCurriculumTypesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string ManageDepartments {
            get {
                return ResourceManager.GetString("ManageDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string ManageDepartmentsIndex {
            get {
                return ResourceManager.GetString("ManageDepartmentsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculties.
        /// </summary>
        public static string ManageFaculties {
            get {
                return ResourceManager.GetString("ManageFaculties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculties.
        /// </summary>
        public static string ManageFacultiesIndex {
            get {
                return ResourceManager.GetString("ManageFacultiesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacultyManageBoards.
        /// </summary>
        public static string ManageFacultyManageBoards {
            get {
                return ResourceManager.GetString("ManageFacultyManageBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacultyManageBoards.
        /// </summary>
        public static string ManageFacultyManageBoardsIndex {
            get {
                return ResourceManager.GetString("ManageFacultyManageBoardsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreSubjects.
        /// </summary>
        public static string ManagePreSubjects {
            get {
                return ResourceManager.GetString("ManagePreSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreSubjects.
        /// </summary>
        public static string ManagePreSubjectsIndex {
            get {
                return ResourceManager.GetString("ManagePreSubjectsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreRecordDetails.
        /// </summary>
        public static string ManageScoreRecordDetails {
            get {
                return ResourceManager.GetString("ManageScoreRecordDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreRecordDetails.
        /// </summary>
        public static string ManageScoreRecordDetailsIndex {
            get {
                return ResourceManager.GetString("ManageScoreRecordDetailsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreRecords.
        /// </summary>
        public static string ManageScoreRecords {
            get {
                return ResourceManager.GetString("ManageScoreRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreRecords.
        /// </summary>
        public static string ManageScoreRecordsIndex {
            get {
                return ResourceManager.GetString("ManageScoreRecordsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semesters.
        /// </summary>
        public static string ManageSemesters {
            get {
                return ResourceManager.GetString("ManageSemesters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semesters.
        /// </summary>
        public static string ManageSemestersIndex {
            get {
                return ResourceManager.GetString("ManageSemestersIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffs.
        /// </summary>
        public static string ManageStaffs {
            get {
                return ResourceManager.GetString("ManageStaffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffs.
        /// </summary>
        public static string ManageStaffsIndex {
            get {
                return ResourceManager.GetString("ManageStaffsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StudentClasses.
        /// </summary>
        public static string ManageStudentClasses {
            get {
                return ResourceManager.GetString("ManageStudentClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StudentClasses.
        /// </summary>
        public static string ManageStudentClassesIndex {
            get {
                return ResourceManager.GetString("ManageStudentClassesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string ManageStudents {
            get {
                return ResourceManager.GetString("ManageStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string ManageStudentsIndex {
            get {
                return ResourceManager.GetString("ManageStudentsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectClasses.
        /// </summary>
        public static string ManageSubjectClasses {
            get {
                return ResourceManager.GetString("ManageSubjectClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectClasses.
        /// </summary>
        public static string ManageSubjectClassesIndex {
            get {
                return ResourceManager.GetString("ManageSubjectClassesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectClassTeachers.
        /// </summary>
        public static string ManageSubjectClassTeachers {
            get {
                return ResourceManager.GetString("ManageSubjectClassTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectClassTeachers.
        /// </summary>
        public static string ManageSubjectClassTeachersIndex {
            get {
                return ResourceManager.GetString("ManageSubjectClassTeachersIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string ManageSubjects {
            get {
                return ResourceManager.GetString("ManageSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string ManageSubjectsIndex {
            get {
                return ResourceManager.GetString("ManageSubjectsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
    }
}
