//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduMSDemo.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduMSDemo.Resources.Shared.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this account?.
        /// </summary>
        public static string AdministratorAccountDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("AdministratorAccountDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this role?.
        /// </summary>
        public static string AdministratorRoleDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("AdministratorRoleDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this setting?.
        /// </summary>
        public static string AdministratorSystemSettingDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("AdministratorSystemSettingDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this BonusScore?.
        /// </summary>
        public static string ManageBonusScoreDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageBonusScoreDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Building?.
        /// </summary>
        public static string ManageBuildingDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageBuildingDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this ClassRoom?.
        /// </summary>
        public static string ManageClassRoomDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageClassRoomDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Course?.
        /// </summary>
        public static string ManageCourseDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageCourseDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Curriculum?.
        /// </summary>
        public static string ManageCurriculumDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageCurriculumDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this CurriculumDetail?.
        /// </summary>
        public static string ManageCurriculumDetailDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageCurriculumDetailDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this CurriculumType?.
        /// </summary>
        public static string ManageCurriculumTypeDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageCurriculumTypeDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Department?.
        /// </summary>
        public static string ManageDepartmentDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageDepartmentDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Faculty?.
        /// </summary>
        public static string ManageFacultyDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageFacultyDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this FacultyManageBoard?.
        /// </summary>
        public static string ManageFacultyManageBoardDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageFacultyManageBoardDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this PreSubject?.
        /// </summary>
        public static string ManagePreSubjectDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManagePreSubjectDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this ScoreRecord?.
        /// </summary>
        public static string ManageScoreRecordDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageScoreRecordDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this ScoreRecordDetail?.
        /// </summary>
        public static string ManageScoreRecordDetailDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageScoreRecordDetailDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Semester?.
        /// </summary>
        public static string ManageSemesterDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageSemesterDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Staff?.
        /// </summary>
        public static string ManageStaffDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageStaffDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this StudentClass?.
        /// </summary>
        public static string ManageStudentClassDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageStudentClassDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Student?.
        /// </summary>
        public static string ManageStudentDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageStudentDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this SubjectClass?.
        /// </summary>
        public static string ManageSubjectClassDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageSubjectClassDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this SubjectClassTeacher?.
        /// </summary>
        public static string ManageSubjectClassTeacherDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageSubjectClassTeacherDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this Subject?.
        /// </summary>
        public static string ManageSubjectDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManageSubjectDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to unregister this subject?.
        /// </summary>
        public static string StudentSubjectUnregisterConfirmMessage {
            get {
                return ResourceManager.GetString("StudentSubjectUnregisterConfirmMessage", resourceCulture);
            }
        }
    }
}
