//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduMSDemo.Resources.Permission.Controller {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduMSDemo.Resources.Permission.Controller.Titles", typeof(Titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AdministrationAccounts {
            get {
                return ResourceManager.GetString("AdministrationAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string AdministrationRoles {
            get {
                return ResourceManager.GetString("AdministrationRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemSettings.
        /// </summary>
        public static string AdministrationSystemSettings {
            get {
                return ResourceManager.GetString("AdministrationSystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BonusScores.
        /// </summary>
        public static string ManageBonusScores {
            get {
                return ResourceManager.GetString("ManageBonusScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildings.
        /// </summary>
        public static string ManageBuildings {
            get {
                return ResourceManager.GetString("ManageBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassRooms.
        /// </summary>
        public static string ManageClassRooms {
            get {
                return ResourceManager.GetString("ManageClassRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string ManageCourses {
            get {
                return ResourceManager.GetString("ManageCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurriculumDetails.
        /// </summary>
        public static string ManageCurriculumDetails {
            get {
                return ResourceManager.GetString("ManageCurriculumDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculums.
        /// </summary>
        public static string ManageCurriculums {
            get {
                return ResourceManager.GetString("ManageCurriculums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurriculumTypes.
        /// </summary>
        public static string ManageCurriculumTypes {
            get {
                return ResourceManager.GetString("ManageCurriculumTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string ManageDepartments {
            get {
                return ResourceManager.GetString("ManageDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculties.
        /// </summary>
        public static string ManageFaculties {
            get {
                return ResourceManager.GetString("ManageFaculties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacultyManageBoards.
        /// </summary>
        public static string ManageFacultyManageBoards {
            get {
                return ResourceManager.GetString("ManageFacultyManageBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreSubjects.
        /// </summary>
        public static string ManagePreSubjects {
            get {
                return ResourceManager.GetString("ManagePreSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreRecordDetails.
        /// </summary>
        public static string ManageScoreRecordDetails {
            get {
                return ResourceManager.GetString("ManageScoreRecordDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreRecords.
        /// </summary>
        public static string ManageScoreRecords {
            get {
                return ResourceManager.GetString("ManageScoreRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scores.
        /// </summary>
        public static string ManageScores {
            get {
                return ResourceManager.GetString("ManageScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semesters.
        /// </summary>
        public static string ManageSemesters {
            get {
                return ResourceManager.GetString("ManageSemesters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffs.
        /// </summary>
        public static string ManageStaffs {
            get {
                return ResourceManager.GetString("ManageStaffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StudentClasses.
        /// </summary>
        public static string ManageStudentClasses {
            get {
                return ResourceManager.GetString("ManageStudentClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string ManageStudents {
            get {
                return ResourceManager.GetString("ManageStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studies.
        /// </summary>
        public static string ManageStudies {
            get {
                return ResourceManager.GetString("ManageStudies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectClasses.
        /// </summary>
        public static string ManageSubjectClasses {
            get {
                return ResourceManager.GetString("ManageSubjectClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectClassTeachers.
        /// </summary>
        public static string ManageSubjectClassTeachers {
            get {
                return ResourceManager.GetString("ManageSubjectClassTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string ManageSubjects {
            get {
                return ResourceManager.GetString("ManageSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        public static string ManageTeachers {
            get {
                return ResourceManager.GetString("ManageTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string StudentSubjectRegister {
            get {
                return ResourceManager.GetString("StudentSubjectRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teaching.
        /// </summary>
        public static string TeacherTeaching {
            get {
                return ResourceManager.GetString("TeacherTeaching", resourceCulture);
            }
        }
    }
}
