// <auto-generated />
namespace EduMSDemo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_schoolyear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_schoolyear));
        
        string IMigrationMetadata.Id
        {
            get { return "201605251542376_remove_schoolyear"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
